version: '3.2'

services:
  terminator:
    image: dollarkiller/creeper:latest
    restart: always
    ports:
      - "8745:8745"
    environment:
      MeilisearchAddr: http://meilisearch:7700
      MeilisearchToken: root
      Token: my_token
    depends_on:
      - meilisearch


  meilisearch:
    image: getmeili/meilisearch:latest
    restart: always
    environment:
      MEILI_MASTER_KEY: root                     # 密钥
      MEILI_MAX_INDEX_SIZE: 307374182400        # 最大索引大小 300G
      MEILI_MAX_UDB_SIZE: 307374182400          # 最大数据库大小 300G
      MEILI_HTTP_PAYLOAD_SIZE_LIMIT: 1048576000  # 最大请求大小 1G
    ports:
      - "7700:7700"
    volumes:
      - ./data.ms:/home/meili/data.ms  # 请给 当前目录777权限
