version: '3.2'

services:
  rlog:
    image: dollarkiller/creeper_rlog:latest
    restart: always
    volumes:
      - ./log/:/app/log/
    environment:
      CreeperAddr: http://192.168.88.203:8745
      CreeperToken: ""
      CreeperIndex: test_index
      LogPath: /app/log/a.log   # TODO 修改此处
